tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "red": {
                    50: "#B70011",
                    100: "#B70011",
                    200: "#B70011",
                    300: "#B70011",
                    400: "#B70011",
                    500: "#B70011",
                    600: "#B70011",
                    700: "#B70011",
                    800: "#B70011",
                    900: "#B70011",
                    950: "#B70011",
                    DEFAULT: "#B70011"
                },
                "secondary-container": "#fed01b",
                "tertiary": "#005e8d",
                "error": "#ba1a1a",
                "on-secondary-fixed-variant": "#574500",
                "on-background": "#191c1d",
                "primary": "#b70011",
                "on-surface": "#191c1d",
                "error-container": "#ffdad6",
                "surface-container-low": "#f3f4f5",
                "surface-container": "#edeeef",
                "tertiary-container": "#0078b2",
                "on-error": "#ffffff",
                "surface": "#f8f9fa",
                "on-surface-variant": "#5c403c",
                "on-tertiary-container": "#f3f8ff",
                "on-primary-fixed": "#410002",
                "secondary": "#fed01b", /* Mustard Yellow */
                "surface-variant": "#e1e3e4",
                "on-secondary-fixed": "#231b00",
                "inverse-on-surface": "#f0f1f2",
                "surface-container-high": "#e7e8e9",
                "outline": "#916f6b",
                "primary-fixed-dim": "#ffb4ab",
                "primary-fixed": "#ffdad6",
                "on-tertiary": "#ffffff",
                "on-error-container": "#93000a",
                "on-secondary": "#ffffff",
                "outline-variant": "#e6bdb8",
                "background": "#f8f9fa",
                "secondary-fixed": "#ffe083",
                "surface-container-lowest": "#ffffff",
                "tertiary-fixed-dim": "#90cdff",
                "on-primary-fixed-variant": "#93000b",
                "on-primary-container": "#fff6f5",
                "on-primary": "#ffffff",
                "tertiary-fixed": "#cbe6ff",
                "inverse-surface": "#2e3132",
                "inverse-primary": "#ffb4ab",
                "surface-container-highest": "#e1e3e4",
                "on-tertiary-fixed": "#001e30",
                "primary-container": "#B70011",
                "surface-tint": "#B70011",
                "on-tertiary-fixed-variant": "#004b71",
                "surface-dim": "#d9dadb",
                "secondary-fixed-dim": "#eec200",
                "on-secondary-container": "#6f5900",
                "surface-bright": "#f8f9fa"
            },
            fontFamily: {
                "headline": ["Newsreader", "serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "0px"},
        },
    },
}
